name: Build & Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      .github/**
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: wp_version
      env:
        WP_VERSION_FILE: style.css
      run: echo "::set-output name=version::$(perl -n -e'/Version:\s*(\d.\d.\d)/ && print $1' $WP_VERSION_FILE)"
    - name: Check wp_version
      if:  ${{ !steps.wp_version.outputs.version}}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('wp_version not set')
    - name: Create a .npmrc file for the github private repository
      uses: FerLuisxd/create-npmrc@3
      with:
        org_name: lig0  
      env:
        AUTH_TOKEN: ${{ secrets.NPMRC_AUTH_TOKEN }}
    - name: Build
      run: |
          npm i
          npm run bundle
    - name: Release
      uses:  softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.wp_version.outputs.version}}
        name: ${{ steps.wp_version.outputs.version}}
        draft: false
        prerelease: false
        files: ./dist/*.zip
