name: Version Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore: .github/**

jobs:
  call-workflow-wp-version-check:
    uses: HfH-DLC/github-workflows/.github/workflows/wp_version_check.yml@main
    with:
      wp_version_file: style.css
      use_package_json: true
